#!/usr/bin/env ruby
require 'redis'

puts Dir.pwd

if ARGV.length > 1
  content = File.open(ARGV[1], "rb").read.gsub("\n", "").gsub("  ", "")
  redis = nil
  if ARGV[2].nil? || ARGV[3].nil?
    redis = Redis.new
  else
    redis = Redis.new(:url => ARGV[2], :password => ARGV[3])
  end
  redis.del(ARGV[0])
  redis.set(ARGV[0], content)
  puts "Write success"
else
  puts "redis-import <keyname> <filename> <optional: url> <optional: password>"
end
